version: "3.1"
services:
  # container_name: "name_wordpress"
  wordpress:
    build: ./wordpress
    ports:
      - "9000:80"
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_HOST: "mariadb:3306"
    volumes:
      - ./public:/var/www/html/wp-content/themes/harim
  mariadb:
    # container_name: "name_db"
    image: mariadb:latest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db-data:/var/lib/mysql
      # - ./database/install_wordpress.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
volumes:
  db-data:
    driver: local
