version: "3.1"
services:
  wordpress:
    container_name: "${PROJECT_NAME}_wordpress"
    build: ./wordpress
    ports:
      - 9000:80
    depends_on:
      - mariadb
    volumes:
      - ./public:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
    env_file: .env
  mariadb:
    container_name: "${PROJECT_NAME}_db"
    ports:
      - 3306:3306
    image: mariadb:latest
    volumes:
      - db-data:/var/lib/mysql
      # - ./database:/docker-entrypoint-initdb.d/install_wordpress.sql
    env_file: .env
  wordmove:
    container_name: "${PROJECT_NAME}_wordmove"
    tty: true
    depends_on:
      - wordpress
    image: welaika/wordmove
    volumes:
      - ./wordmove:/home/wordmove
      - ./public:/var/www/html
      - ~/.ssh:/home/wordmove/.ssh
    env_file: .env
volumes:
  db-data:
    driver: local
